{% set name = "suggestion" %}
{% set version = "0.0.7" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/suggestion-{{ version }}.tar.gz
  sha256: 7f7e0ac7725b82f1b2c000447478ffc017588a4d79d7e1160542eca6514f67c0

build:
  entry_points:
    - suggestion = suggestion.__main__:main
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv
  number: 0

requirements:
  host:
    - pip
    - python >=3.5
  run:
    - python >=3.5
    - viewable

test:
  imports:
    - suggestion
  commands:
    - pip check
    - suggestion --help
  requires:
    - pip

about:
  home: https://github.com/pyrustic/suggestion
  summary: Democratizing auto-complete(suggest) for Python desktop applications
  license: MIT
  license_file:
    - LICENSE

extra:
  recipe-maintainers:
    - thewchan
